parameters:
  - name: apiVersion
    type: string
    values:
      - apigeeapi
      - googleapi
  - name: buildStageName
    type: string
    default: Build

jobs:
  - template: ../jobs/functional-testing.yaml
    parameters:
      apiVersion: ${{ parameters.apiVersion }}
      buildStageName: ${{ parameters.buildStageName }}
