trigger:
  branches:
    include:
      - "*"
  paths:
    exclude:
      - "docs/**"
      - ".gitignore"
      - "README.md"

resources:
  repositories:
    - repository: self
      clean: true
    - repository: apigee-core
      type: github
      name: ShehabEl-DeenAlalkamy/apigee-core-yaml-pipeline-templates
      ref: feat/api-proxy-framework
      endpoint: ShehabEl-DeenAlalkamy

pool:
  vmImage: ubuntu-latest

extends:
  template: build-01.yaml@apigee-core
  parameters:
    variableGroups:
      - abomis-airports-common
