trigger: none

pr: none

resources:
  repositories:
    - repository: self
      clean: true
    - repository: apigee-core
      type: github
      name: ShehabEl-DeenAlalkamy/apigee-core-yaml-pipeline-templates
      # TODO: uncomment when work is done
      # ref: main
      # TODO: remove when development is done
      ref: rel/framework-v2.0.0
      endpoint: ShehabEl-DeenAlalkamy
  pipelines:
    - pipeline: abomis-airports-ci
      source: abomis-airports-ci
      trigger:
        branches:
          include:
            # TODO: uncomment when work is done
            # - main
            # TODO: remove when development work is done
            - release/abomis-airports-v2.1.0-beta

pool:
  vmImage: ubuntu-latest

extends:
  template: release.yaml@apigee-core
  parameters:
    releaseProfile: custom-release
    deploymentProfile:
      type: api-proxies
      name: mvn-plugins
      version: 1
    artifactAlias: abomis-airports-ci
    artifactName: proxy-bundle-artifacts
    commonVariableGroups:
      - abomis-airports-common
    releaseList:
      - stageName: Dev
        displayName: Dev
        variableGroups:
          - abomis-airports-dev-env
        environment: abomis-dev
      - stageName: Test
        displayName: Test
        variableGroups:
          - abomis-airports-tst-env
        environment: abomis-tst
      - stageName: Prod
        displayName: Prod
        variableGroups:
          - abomis-airports-prd-env
        environment: abomis-prd
