parameters:
  - name: apiVersion
    type: string
    values:
      # Apigee Edge
      - apigeeapi
      # Apigee X or Hybrid
      - googleapi
  - name: preBuildStageName
    type: string
    default: PreBuild
  - name: preBuildStageDisplayName
    type: string
    default: PreBuild
  - name: buildStageName
    type: string
    default: Build
  - name: buildStageDisplayName
    type: string
    default: Build
  - name: postBuildStageName
    type: string
    default: PostBuild
  - name: postBuildStageDisplayName
    type: string
    default: PostBuild
  - name: defaultBranch
    type: string
    default: main

stages:
  - stage: ${{ parameters.preBuildStageName }}
    displayName: ${{ parameters.preBuildStageDisplayName }}
    jobs:
      - template: job-groups/systems-checks.yaml

  - stage: ${{ parameters.buildStageName }}
    displayName: ${{ parameters.buildStageDisplayName }}
    condition: |
      succeeded('${{ parameters.preBuildStageName }}')
    dependsOn:
      - ${{ parameters.preBuildStageName }}
    jobs:
      - template: job-groups/custom-build.yaml
        parameters:
          apiVersion: ${{ parameters.apiVersion }}

  - stage: ${{ parameters.postBuildStageName }}
    displayName: ${{ parameters.postBuildStageDisplayName }}
    condition: |
      succeeded('${{ parameters.buildStageName }}')
    dependsOn:
      - ${{ parameters.buildStageName }}
    jobs:
      - template: job-groups/post-build.yaml
        parameters:
          apiVersion: ${{ parameters.apiVersion }}
          buildStageName: ${{ parameters.buildStageName }}
