parameters:
  - name: jobName
    type: string
    default: FuncTesting
  - name: displayName
    type: string
    default: Functional Testing
  - name: artifactAlias
    type: string
  - name: artifactName
    type: string
  - name: dependsOn
    type: object
    default: []
  - name: mandatoryTasks
    type: stepList
    default: []

jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.displayName }}
    dependsOn:
      - ${{ each dependency in parameters.dependsOn }}:
          - ${{ dependency }}
    steps:
      - ${{ parameters.mandatoryTasks }}

      - template: ../steps/export-scripts-path.yaml
        parameters:
          isReleaseFlow: true

      - download: ${{ parameters.artifactAlias }}
        artifact: ${{ parameters.artifactName }}
        displayName: Download ${{ parameters.artifactName }}

      - script: |
          echo org      : "${ORG}"
          echo env      : "${ENV}"
          echo hostname : "${HOSTNAME}"
        displayName: Show Vars

      - task: CopyFiles@2
        displayName: Copy Artifacts to Build Sources Directory
        inputs:
          SourceFolder: $(Pipeline.Workspace)/${{ parameters.artifactAlias }}/${{ parameters.artifactName }}
          Contents: "**"
          TargetFolder: $(Build.SourcesDirectory)
          OverWrite: true

      - task: NodeTool@0
        displayName: "Install Node 18.0.0"
        inputs:
          versionSpec: 18.0.0

      - task: Npm@1
        displayName: "npm install"
        inputs:
          verbose: false

      - bash: |
          readonly ADO_DEBUG_CMD="##[debug]"
          export PATH_TO_TARGET=./target
          echo "${ADO_DEBUG_CMD}"creating "${BUILD_ARTIFACTSTAGINGDIRECTORY}"/functional-testing/cucumber      
          mkdir -p ./functional-testing/cucumber
          echo "TEST_HOST=${HOST_NAME} node node_modules/.bin/cucumber-js --publish-quiet "${PATH_TO_TARGET}"/test/integration --format html:./functional-testing/cucumber/report.html"
          TEST_HOST="${HOST_NAME}" node node_modules/.bin/cucumber-js --publish-quiet "${PATH_TO_TARGET}"/test/integration --format html:./functional-testing/cucumber/report.html
        displayName: "FT: CucumberJS"
        env:
          HOST_NAME: $(hostname)

      - task: PublishBuildArtifacts@1
        displayName: "Publish: Functional Tests Results"
        inputs:
          pathToPublish: ./functional-testing
          artifactName: functional-testing-${{ parameters.EnvName }}
