parameters:
  - name: jobName
    type: string
    default: FuncTesting
  - name: displayName
    type: string
    default: Functional Testing
  - name: artifactAlias
    type: string
  - name: artifactName
    type: string
  - name: dependsOn
    type: object
    default: []
  - name: mandatoryTasks
    type: stepList
    default: []

jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.displayName }}
    dependsOn:
      - ${{ each dependency in parameters.dependsOn }}:
          - ${{ dependency }}
    steps:
      - template: ../steps/export-scripts-path.yaml
        parameters:
          isReleaseFlow: true

      - download: ${{ parameters.artifactAlias }}
        artifact: ${{ parameters.artifactName }}
        displayName: Download ${{ parameters.artifactName }}

      - ${{ parameters.mandatoryTasks }}

      - script: |
          echo org      : "${ORG}"
          echo env      : "${ENV}"
          echo hostname : "${HOSTNAME}"
        displayName: Show Vars

      - task: CopyFiles@2
        displayName: Copy Artifacts to Build Sources Directory
        inputs:
          SourceFolder: $(Pipeline.Workspace)/${{ parameters.artifactAlias }}/${{ parameters.artifactName }}
          Contents: "**"
          TargetFolder: $(Build.SourcesDirectory)
          OverWrite: true     
