parameters:
  - name: jobName
    type: string
    default: UnitTesting
  - name: displayName
    type: string
    default: Unit Testing
  - name: dependsOn
    type: object
    default: []
  - name: mandatoryTasks
    type: stepList
    default: []

jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.displayName }}
    dependsOn:
      - ${{ each dependency in parameters.dependsOn }}:
          - ${{ dependency }}
    steps:
      - ${{ parameters.mandatoryTasks }}

      - checkout: self
        path: s/$(Build.Repository.Name)
        persistCredentials: true

      - task: Npm@1
        displayName: npm install
        inputs:
          command: install

      - bash: |
          echo "./node_modules/nyc/bin/nyc.js --reporter=html --reporter=text ./node_modules/mocha/bin/_mocha --timeout 5000 --recursive ./test/unit"
          mkdir -p "${BUILD_ARTIFACTSTAGINGDIRECTORY}"/utests/jsc
          ./node_modules/nyc/bin/nyc.js --reporter=html --reporter=text ./node_modules/mocha/bin/_mocha --timeout 5000 --recursive ./test/unit
          cp coverage/* "${BUILD_ARTIFACTSTAGINGDIRECTORY}"/utests/jsc/
        displayName: "UT: JavaScript Resources"

      - task: PublishBuildArtifacts@1
        displayName: "Publish: Tests Results"
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)/utests
          artifactName: unit-testing

      - bash: |
          readonly ADO_DEBUG_CMD="##[debug]"
          echo "${ADO_DEBUG_CMD}"deleting "${BUILD_ARTIFACTSTAGINGDIRECTORY}"/utests.
          rm -rf "${BUILD_ARTIFACTSTAGINGDIRECTORY}"/utests
        displayName: Artifacts Cleaning
